# Generated by Django 5.2.5 on 2025-08-21 09:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('generate_text', 'Generate Text'), ('view_history', 'View History'), ('view_transition_analysis', 'View Transition Analysis'), ('view_coherence_report', 'View Coherence Report'), ('register', 'Register'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('login_successful', models.BooleanField(default=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Login Log',
                'verbose_name_plural': 'User Login Logs',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='generatedtext',
            options={'ordering': ['-created_at'], 'verbose_name': 'Generated Text', 'verbose_name_plural': 'Generated Texts'},
        ),
        migrations.AddField(
            model_name='generatedtext',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedtext',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_texts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='generatedtext',
            index=models.Index(fields=['user', '-created_at'], name='main_genera_user_id_090a79_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedtext',
            index=models.Index(fields=['session_key', '-created_at'], name='main_genera_session_fe0817_idx'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userloginlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', '-timestamp'], name='main_userac_user_id_8cf312_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['action', '-timestamp'], name='main_userac_action_caf4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['session_key', '-timestamp'], name='main_userac_session_a2f5d6_idx'),
        ),
    ]
