# Generated by Django 5.2.5 on 2025-09-20 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_useractivitylog_userloginlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initializing', 'Initializing'), ('generating', 'Generating'), ('correcting', 'Correcting Grammar'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_step', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=5)),
                ('percentage', models.FloatField(default=0.0)),
                ('current_sentence', models.IntegerField(default=0)),
                ('total_sentences', models.IntegerField(default=5)),
                ('model_type', models.CharField(default='standard', max_length=50)),
                ('status_message', models.CharField(blank=True, max_length=200)),
                ('detailed_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('input_text', models.TextField(blank=True)),
                ('generated_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generation Progress',
                'verbose_name_plural': 'Generation Progress',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='generatedtext',
            name='progress_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result', to='main.generationprogress'),
        ),
        migrations.AddIndex(
            model_name='generationprogress',
            index=models.Index(fields=['task_id'], name='main_genera_task_id_f1ef65_idx'),
        ),
        migrations.AddIndex(
            model_name='generationprogress',
            index=models.Index(fields=['session_key', '-started_at'], name='main_genera_session_ee83ad_idx'),
        ),
        migrations.AddIndex(
            model_name='generationprogress',
            index=models.Index(fields=['user', '-started_at'], name='main_genera_user_id_d86876_idx'),
        ),
    ]
