# Generated by Django 5.2.5 on 2025-09-20 20:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_generationprogress_generatedtext_progress_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generationprogress',
            options={'ordering': ['-start_time'], 'verbose_name': 'Generation Progress', 'verbose_name_plural': 'Generation Progress'},
        ),
        migrations.RemoveIndex(
            model_name='generationprogress',
            name='main_genera_session_ee83ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='generationprogress',
            name='main_genera_user_id_d86876_idx',
        ),
        migrations.RenameField(
            model_name='generationprogress',
            old_name='estimated_completion',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='generationprogress',
            old_name='detailed_message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='generatedtext',
            name='progress_task',
        ),
        migrations.RemoveField(
            model_name='generationprogress',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='generationprogress',
            name='input_text',
        ),
        migrations.RemoveField(
            model_name='generationprogress',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='generationprogress',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='generationprogress',
            name='status_message',
        ),
        migrations.RemoveField(
            model_name='generationprogress',
            name='total_steps',
        ),
        migrations.RemoveField(
            model_name='generationprogress',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='generationprogress',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='generationprogress',
            name='generated_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='main.generatedtext'),
        ),
        migrations.AlterField(
            model_name='generationprogress',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='generationprogress',
            name='task_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='generationprogress',
            name='total_sentences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='generationprogress',
            index=models.Index(fields=['user', '-start_time'], name='main_genera_user_id_764172_idx'),
        ),
        migrations.AddIndex(
            model_name='generationprogress',
            index=models.Index(fields=['session_key', '-start_time'], name='main_genera_session_5e458e_idx'),
        ),
        migrations.AddIndex(
            model_name='generationprogress',
            index=models.Index(fields=['status', '-start_time'], name='main_genera_status_1d4846_idx'),
        ),
    ]
